# Shared test fixtures derived from the real Sant Pau HAR capture
# (recorded 2026-05-01, Firefox 149.0)

# Raw activities list as returned by elem=activitats
MOCK_ACTIVITIES_API_RESPONSE = [
    {
        "codi": "1",
        "hihaPlaces": 1250878,
        "calendarFutur": "",
        "desc": "Visita Lliure ",
        "edatMin": "0",
        "edatMax": "99",
        "capacidad": "9",
        "mesInfo": "El Recinte Modernista es pot visitar lliurement.",
        "mesInfoCurta": "El Recinte Modernista es pot visitar lliurement.",
        "imatge": "ok",
        "preu": "126.00",
        "capacidadMin": "1",
        "posGrup": "1",
        "tipus": "S",
        "primerMes": "01/05/2026",
        "ultimMes": "31/12/2026",
        "activitats": "",
        "elimCombi": "",
        "cicle": "",
        "sugerencia": [],
        "calendariWeb": "S",
    },
    {
        "codi": "2",
        "hihaPlaces": 5049,
        "calendarFutur": "",
        "desc": "Visita Guiada",
        "edatMin": "0",
        "edatMax": "99",
        "capacidad": "9",
        "mesInfo": "Amb la visita guiada podreu fer el recorregut habitual.",
        "mesInfoCurta": "Amb la visita guiada podreu fer el recorregut.",
        "imatge": "ok",
        "preu": "21.00",
        "capacidadMin": None,
        "posGrup": "2",
        "tipus": "S",
        "primerMes": "01/05/2026",
        "ultimMes": "27/12/2026",
        "activitats": "",
        "elimCombi": "",
        "cicle": "",
        "sugerencia": [],
        "calendariWeb": "S",
    },
    {
        "codi": "0-8",
        "hihaPlaces": 926992,
        "calendarFutur": "",
        "desc": "Visita Lliure  amb audioguia interactiva",
        "edatMin": "0",
        "edatMax": "99",
        "capacidad": "5",
        "mesInfo": "Visita lliure amb audioguia.",
        "mesInfoCurta": "Visita lliure amb audioguia.",
        "imatge": "ok",
        "preu": "180.00",
        "capacidadMin": "1",
        "posGrup": "3",
        "tipus": "COMBI",
        "primerMes": "01/05/2026",
        "ultimMes": "31/12/2026",
        "activitats": "",
        "elimCombi": "",
        "cicle": "",
        "sugerencia": [],
        "calendariWeb": None,
    },
]

# Raw horaris response for activity "1" on 2026-05-02 (from HAR entry 10)
# Includes: limited sessions (93–96% full), a sold-out session (100%),
# and a special session with null totalPers.
# Raw horaris response for activity "1" on 2026-05-02 (from HAR entry 10)
#
# IMPORTANT — nPers / percPers field semantics:
#   nPers    = seats STILL AVAILABLE for booking
#   percPers = percentage of capacity that is STILL AVAILABLE
# This is the opposite of what the names suggest; confirmed empirically
# by comparing the website's occupancy bar-chart icons to the raw values.
#
# Includes: limited sessions (7–5% available = 93–95% occupied),
# an available session (90% available = 10% occupied),
# a sold-out session (0% available = 100% occupied),
# and a special session with null totalPers (unknown status).
MOCK_HORARIS_API_RESPONSE = [
    {
        "codi": "1",
        "portesObertes": "N",
        "tipus": "NORMAL",
        "codiCombi": "0",
        "desc": "Visita Lliure ",
        "mostrIdioma": "S",
        "error": "",
        "sessions": [
            # Limited: 7% available (93% occupied) — just 25 seats left
            {
                "numSessio": "23",
                "idioma": "0",
                "horaInici": "0930",
                "horaFi": "1000",
                "nomesCombi": None,
                "portesObertes": "N",
                "temporada": "2025 ",
                "identInt": None,
                "totalPers": 350,
                "nPers": 25,
                "percPers": 7.0,
            },
            # Limited: 5% available (95% occupied) — just 18 seats left
            {
                "numSessio": "1",
                "idioma": "0",
                "horaInici": "1000",
                "horaFi": "1030",
                "nomesCombi": None,
                "portesObertes": "N",
                "temporada": "2025 ",
                "identInt": None,
                "totalPers": 350,
                "nPers": 18,
                "percPers": 5.0,
            },
            # Available: 90% available (10% occupied) — 315 seats free
            {
                "numSessio": "99",
                "idioma": "0",
                "horaInici": "1100",
                "horaFi": "1130",
                "nomesCombi": None,
                "portesObertes": "N",
                "temporada": "2025 ",
                "identInt": None,
                "totalPers": 350,
                "nPers": 315,
                "percPers": 90.0,
            },
            # Sold out: 0% available (100% occupied) — no seats left
            {
                "numSessio": "10",
                "idioma": "0",
                "horaInici": "1430",
                "horaFi": "1500",
                "nomesCombi": None,
                "portesObertes": "N",
                "temporada": "2025 ",
                "identInt": None,
                "totalPers": 350,
                "nPers": 0,
                "percPers": 0.0,
            },
            # Unknown: null totalPers (special/combo session)
            {
                "numSessio": "24",
                "idioma": "0",
                "horaInici": "1730",
                "horaFi": "1800",
                "nomesCombi": "N",
                "portesObertes": "N",
                "preu": None,
                "temporada": None,
                "identInt": None,
                "nPers": 0,
                "totalPers": None,
                "percPers": 0,
            },
        ],
    }
]

# Raw calendar response for May 2026 (from HAR entry 3, truncated for tests)
MOCK_CALENDAR_API_RESPONSE = [
    {"fecha": "2026-05-01", "tipus": "EST", "portesObertes": "N", "comentariCal": []},
    {"fecha": "2026-05-02", "tipus": "EST", "portesObertes": "N", "comentariCal": []},
    # Free admission day
    {"fecha": "2026-05-03", "tipus": "EST", "portesObertes": "S", "comentariCal": []},
    # No availability (fully sold out / closed)
    {"fecha": "2026-05-27", "tipus": "senseLloc", "portesObertes": "N", "comentariCal": []},
    {"fecha": "2026-05-28", "tipus": "senseLloc", "portesObertes": "N", "comentariCal": []},
    {"fecha": "2026-05-29", "tipus": "EST", "portesObertes": "N", "comentariCal": []},
]

# Raw getTarifes response for activity "1", 16/05/2026, hora 1100
# (derived from sant-pau-preus.har, entry 16)
MOCK_TARIFES_API_RESPONSE = [
    {
        "codi": 1,
        "numAdult": "1",
        "numNen": "0",
        "desc": "General",
        "observ": "",
        "amic": "N",
        "identifServei": "0",
        "preu": "18.00",
        "preuOriginal": "17.00",
        "posInternet": 1,
        "abonament": "N",
        "minPers": None,
        "maxPers": None,
        "favorita": "S",
        "portesObertes": "N",
        "opcioBescanvi": True,
    },
    {
        "codi": 21,
        "numAdult": "1",
        "numNen": "0",
        "desc": "Amics del Recinte Modernista",
        "observ": "Tarifa gratuïta per a titulars del carnet d'Amic Veí.",
        "amic": "S",
        "identifServei": "0",
        "preu": "0.00",
        "preuOriginal": "0.00",
        "posInternet": 99,
        "abonament": "N",
        "minPers": None,
        "maxPers": None,
        "favorita": "N",
        "portesObertes": "N",
        "opcioBescanvi": True,
    },
    {
        "codi": 5,
        "numAdult": "1",
        "numNen": "0",
        "desc": "Menors 12 anys",
        "observ": "Accés gratuït per a menors de 12 anys.",
        "amic": "N",
        "identifServei": "0",
        "preu": "0.00",
        "preuOriginal": "0.00",
        "posInternet": 99,
        "abonament": "N",
        "minPers": 1,
        "maxPers": 4,
        "favorita": "N",
        "portesObertes": "N",
        "opcioBescanvi": False,
    },
    {
        "codi": 99,
        "numAdult": "1",
        "numNen": "0",
        "desc": "Portes Obertes Special",
        "observ": "Only valid on free-admission days.",
        "amic": "N",
        "identifServei": "0",
        "preu": "0.00",
        "preuOriginal": "0.00",
        "posInternet": 99,
        "abonament": "N",
        "minPers": None,
        "maxPers": None,
        "favorita": "N",
        "portesObertes": "S",
        "opcioBescanvi": False,
    },
]
